apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: knative-group
  bootstrapServers: kafka-cp-kafka-headless.kafka:9092 #note the kafka namespace
  topics: knative-demo-topic
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
    name: default